title: ESFM Tesla GFNY Training
description: Standardized frontline SOPs, route cards, and checklists for Tesla GFNY EVS.
remote_theme: just-the-docs/just-the-docs

# Site-wide settings
logo: /assets/img/logo.png
search_enabled: true
color_scheme: nil

# Navigation helpers
aux_links:
  ESFM Sharepoint Site: https://cpgplc.sharepoint.com/sites/esfmtgfny/SitePages/CollabHome.aspx
  EVS Daily Shift Log: https://cpgplc.sharepoint.com/sites/esfmtgfny/_layouts/15/listforms.aspx?cid=ZDk0MzVjMmMtMjdhNi00ZGUzLTkxMTctYWM4YmZmYTE5NWI2&nav=ZjY1NDRhY2EtOTI5Ny00NWYxLWIyODctMDZlY2QzNzBhZDhl
  Incoming Manager Handoff: https://cpgplc.sharepoint.com/sites/esfmtgfny/_layouts/15/listforms.aspx?cid=ZWExNzk0ODgtN2M5ZS00OWFkLThjOWQtZjhlMDVlMWUyY2Rj&nav=Y2I0NmJmZDgtMGRiNS00MmUyLThkMmYtMWVhYzM1ZTA4NTFk
  Outgoing Manager Handoff: https://cpgplc.sharepoint.com/sites/esfmtgfny/_layouts/15/listforms.aspx?cid=OGY3MjY0OTctMjI4Mi00MDMyLTgxNTEtZTg0ZjE2NTc2MTQ1&nav=OThmZTM0OGYtMjY0Zi00YWEzLTg3OTctNmNkMzdiZjMwMzIz

# Footer
footer_content: "© ESFM / Compass Group — Internal use for Tesla GFNY. Last updated: {{ site.time | date: '%Y-%m-%d' }}"
